Style/AccessorMethodName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# New Cops
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: false
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
